### PR TITLE
* allow custom model

### PR DESCRIPTION
**Pull request by aaarrti**
### Description
- Right now, user can only use `TensorFlowModel` or `PyTorchModel` from `quantus`
- If user wants to evaluate, e.g, baseline (sklearn) model, there is no way

### Implemented changes
  - [x] Allow custom implementers of `ModelInterface`

### CODE REVIEW

**Review by annahedstroem — COMMENTED** [review]
Could there be any functions calling this function where this statement needs to hold true, i.e., where we want to return the ModelInterface from this function? @aaarrti

**Comment by aaarrti** [comment]
> Could there be any functions calling this function where this statement needs to hold true, i.e., where we want to return the ModelInterface from this function? @aaarrti



> Could there be any functions calling this function where this statement needs to hold true, i.e., where we want to return the ModelInterface from this function? @aaarrti


Hi, 
the use case for this is custom implementations of ModelInterface provided by user, smth like: 

```python
import quantus

class MyOwnCustomModel(quantus.ModelInterface):

   """
   User-defined wrapper around model, 
   which is not supported out of the box by Quantus
   """

   def predict(x_batch, **kwargs):
       ...


model = MyOwnCustomModel()
scores = quantus.RandomLogit()(model, ...)       

```

**Comment by annahedstroem** [comment]
hi @aaarrti great example! can you formulate that as a test case? that would be golden!

**Comment by aaarrti** [comment]
Hi @annahedstroem, 
this tiny PR was meant as a demonstration for @abarbosa94 on how we could enable custom user defined models. Unfortunately, I barely have any free time lately, so I will not be able to fully develop tests case and demo notebook showcasing custom models support. As this is a tiny change, I think it can easily be made when it is actually needed. So, I will close the PR 🙃

**Pull request closed without merging**
