### PR TITLE
Add tests for tabular (2D) data

### PR DESCRIPTION
**Pull request by aaarrti**
### Description
- This is a PR for #187 
- Added toy models
- Added test cases for randomization and complexity metrics

### Notes
- TF-explain does not support 2D data, so I just used a stub function. We could look if other library supports 2D shapes, or add our implementation for few baseline methods.

### CODE REVIEW

**Comment by annahedstroem** [comment]
Thanks, Artem. Can you double-check that we can run these notebooks (given update to complexity metrics):

- [ ] https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Time_Series_Data.ipynb
- [ ] https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Tabular_Data.ipynb

**Comment by aaarrti** [comment]
> Thanks, Artem. Can you double-check that we can run these notebooks (given update to complexity metrics):
> 
> * [ ]  https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Time_Series_Data.ipynb
> * [ ]  https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Tabular_Data.ipynb
> 
> (will review after)

Hi, yes, we still can, both of them only showcase `ModelParameterRandomisation` metric. 
Assuming we have sufficient coverage, no failing tests mean no breaking changes to existing metrics.

**Comment by aaarrti** [comment]
> Thanks, Artem. Can you double-check that we can run these notebooks (given update to complexity metrics):
> 
> * [ ]  https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Time_Series_Data.ipynb
> * [ ]  https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started_with_Tabular_Data.ipynb
> 
> (will review after)

Update: I have added an example with `Complexity` metric to these two notebooks.

**Comment by annahedstroem** [comment]
What is the status on this one @aaarrti ?

**Review by annahedstroem — COMMENTED** [review]
Looks good. Let's merge.

**Pull request merged**
